theme = "everforest_dark"

[editor]
cursorline = true
preview-completion-insert = false
line-number = "relative" 

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"

[keys.normal.g]
a = "code_action"
c = "toggle_comments"

[keys.normal.space]
space = "file_picker"

[keys.select.g]
c = "toggle_comments"

