# Inserts a blank line between shell prompts
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol   = "[âœ](bold red)" 
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold  blue dimmed"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[java]
disabled = true

[scala]
format = "via [$symbol](red)[$version]($style)"
style = "red dimmed"
disabled = true

[golang]
format = "via [$symbol](cyan dimmed)[$version](cyan dimmed)" 
symbol = "Ê•â—”Ï–â—”Ê”"
disabled = true


[nodejs]
format = 'via [$symbol($version )]($style)'
disabled = true


[helm]
disabled = false
style = "yellow dimmed"
detect_folders = ["helm-charts"]

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "on [$symbol$branch]($style)"
style = "bold green"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "ğŸ‘Š"
ahead = "ğŸï¸ ğŸ’¨Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${coun}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${coun}"
style = "bright white"
format = "$all_status$ahead_behind "

[gcloud]
format = 'on [$symbol$project(\($region\))]($style)'
disabled = true

[aws]
format = 'on [$symbol $profile | $region \[$duration\]]($style)'


[kubernetes]
symbol = "â˜¸ "
disabled = true
style = "bold blue"


