k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: true
  ui:
    enableMouse: true
    headless: true
    logoless: true
    crumbsless: true
    reactive: true
    skin: everforest
    defaultsToFullScreen: true
    noIcons: false
  skipLatestRevCheck: false
  disablePodCounting: false
  logger:
    tail: 1000
    buffer: 5000
    textWrap: true
    showTime: false
  thresholds:
    cpu:
      critical: 99
      warn: 95
    memory:
      critical: 99
      warn: 95
